# Generated by Django 4.1.1 on 2022-09-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=2000)),
                ('tag', models.CharField(choices=[('BU', 'Bug'), ('IMP', 'Amélioration'), ('TA', 'Tache')], max_length=255)),
                ('priority', models.CharField(choices=[('HP', 'Faible'), ('IP', 'Moyenne'), ('LP', 'Élevée')], max_length=255)),
                ('status', models.CharField(choices=[('TBD', 'A faire'), ('OG', 'En cours'), ('DO', 'Terminé')], max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2000)),
                ('type', models.CharField(choices=[('BE', 'back-end'), ('FE', 'front-end'), ('IOS', 'iOS'), ('ANDROID', 'Android')], max_length=255)),
            ],
        ),
    ]
